SELECT COUNT(BENEFICIARY.Tax_ID)
FROM BENEFICIARY JOIN REGISTERED ON BENEFICIARY.Tax_ID = REGISTERED.Tax_ID JOIN VOUCHER_CLASS ON REGISTERED.Class_ID = VOUCHER_CLASS.Class_ID
WHERE Status='Σε Προγραμματισμό' 
