CREATE TABLE CALL_STATISTICS(
CALL_ID NUMBER NOT NULL,
Beneficiaries_Num NUMBER NOT NULL,
Beneficiaries_Incl_Num NUMBER NOT NULL
);

ALTER TABLE CALL_STATISTICS
ADD CONSTRAINT CALL_ID_PK PRIMARY KEY(CALL_ID);

ALTER TABLE CALL_STATISTICS
ADD CONSTRAINT CALL_STATISTICS_FK
   FOREIGN KEY (CALL_ID)
   REFERENCES VOUCHER_CALL(CALL_ID);

CREATE VIEW Benef_Num AS 
SELECT CALL_ID, COUNT(CALL_ID) AS "BENEF_NUM"
FROM INCLUDED
GROUP BY CALL_ID;

CREATE VIEW Benef_Included_Num AS
SELECT CALL_ID, COUNT(CALL_ID) AS "BENEF_IN_COLNUMN"
FROM SEL
GROUP BY CALL_ID;

INSERT INTO CALL_STATISTICS
SELECT Benef_Included_Num.CALL_ID, BENEF_NUM, BENEF_IN_COLNUMN
FROM Benef_Included_Num
LEFT OUTER JOIN Benef_Num
ON Benef_Num.CALL_ID = Benef_Included_Num.CALL_ID
ORDER BY Benef_Num.CALL_ID;