CREATE OR REPLACE VIEW COMPLETED_OR_IN_IMPLEMENTATION AS
SELECT BENEFICIARY.TAX_ID, UNEMPLOYMENT_CARD, FULL_NAME, BIRTH_YEAR, SEX, HOME_ADDRESS
FROM BENEFICIARY JOIN REGISTERED ON BENEFICIARY.TAX_ID = REGISTERED.TAX_ID JOIN VOUCHER_CLASS ON REGISTERED.CLASS_ID = VOUCHER_CLASS.CLASS_ID
WHERE STATUS='Ολοκληρωμένο' OR STATUS='Σε Υλοποίηση';


SELECT DISTINCT INCLUDED.TAX_ID, FULL_NAME, COUNT(CALL_ID)
FROM COMPLETED_OR_IN_IMPLEMENTATION JOIN INCLUDED ON COMPLETED_OR_IN_IMPLEMENTATION.TAX_ID = INCLUDED.TAX_ID
GROUP BY INCLUDED.TAX_ID, FULL_NAME, CALL_ID
HAVING COUNT(CALL_ID)>1
ORDER BY FULL_NAME DESC;
