SELECT BENEFICIARY.TAX_ID, FULL_NAME
FROM TRAINING_CENTER JOIN INCLUDED ON TRAINING_CENTER.CENTER_ID = INCLUDED.CENTER_ID JOIN BENEFICIARY ON INCLUDED.TAX_ID = BENEFICIARY.TAX_ID
WHERE CALL_ID=1 AND TITLE = 'Κατάρτιση Α.Ε.'
