SELECT TAX_ID, SEX, TO_NUMBER(TO_CHAR(sysdate, 'YYYY')) - BIRTH_YEAR AS AGE 
FROM BENEFICIARY
WHERE TO_NUMBER(TO_CHAR(sysdate, 'YYYY')) - BIRTH_YEAR >= 20 
AND TO_NUMBER(TO_CHAR(sysdate, 'YYYY')) - BIRTH_YEAR <= 29
