SELECT SUM(Voucher_Value), VOUCHER_CALL.Call_ID, Budget
FROM VOUCHER_CALL JOIN INCLUDED ON VOUCHER_CALL.Call_ID = INCLUDED.Call_ID JOIN BENEFICIARY ON BENEFICIARY.Tax_ID = INCLUDED.Tax_ID
GROUP BY INCLUDED.Call_ID, VOUCHER_CALL.Call_ID, Budget
