CREATE OR REPLACE VIEW EROTIMA_7 AS
SELECT SUM(Voucher_Value) AS SUM_OF_VOUCHER_VALUE, VOUCHER_CALL.Call_ID, Budget
FROM VOUCHER_CALL JOIN INCLUDED ON VOUCHER_CALL.Call_ID = INCLUDED.Call_ID JOIN BENEFICIARY ON BENEFICIARY.Tax_ID = INCLUDED.Tax_ID
GROUP BY INCLUDED.Call_ID, VOUCHER_CALL.Call_ID, Budget;

SELECT CALL_ID, BUDGET, SUM_OF_VOUCHER_VALUE
FROM EROTIMA_7 WHERE SUM_OF_VOUCHER_VALUE IN
(SELECT MAX(SUM_OF_VOUCHER_VALUE)
FROM EROTIMA_7);
