CREATE OR REPLACE VIEW erwtima13A AS
 SELECT VOUCHER_ID, Tax_ID, SEL.Call_ID, Voucher_Value
 FROM SEL JOIN VOUCHER_CALL ON SEL.CALL_ID = VOUCHER_CALL.CALL_ID;

CREATE OR REPLACE VIEW erwtima13B AS
 SELECT DISTINCT VOUCHER_ID, SEL.Tax_ID, SEL.Call_ID AS CALL_ID2, Voucher_Value
 FROM SEL
JOIN VOUCHER_CALL ON SEL.CALL_ID = VOUCHER_CALL.CALL_ID
JOIN VOUCHER_CLASS ON VOUCHER_CLASS.CALL_ID = VOUCHER_CALL.CALL_ID
 WHERE STATUS = 'Ολοκληρωμένο';


 SELECT VOUCHER_ID, Tax_ID, Call_ID, Voucher_Value 
FROM erwtima13A  WHERE Call_ID NOT IN (SELECT CALL_ID2 FROM erwtima13B);
