SELECT DISTINCT BENEFICIARY.Tax_ID, FULL_NAME, BIRTH_YEAR
FROM SEL JOIN BENEFICIARY ON BENEFICIARY.Tax_ID = SEL.Tax_ID  
WHERE BENEFICIARY.TAX_ID NOT IN 
(SELECT BENEFICIARY.Tax_ID 
FROM SEL JOIN BENEFICIARY ON BENEFICIARY.Tax_ID = SEL.Tax_ID 
WHERE CALL_ID=4)
